name: MP_optimisation
channels:
 - conda-forge
 - defaults
dependencies:
- python=3.10 
- numpy
- matplotlib
- pathlib
- ipykernel
- scipy
- hvplot
- jupyterlab
- pyomo
- ipopt
- nlopt
- glpk
- pip
- pip:
  - pulp
  - openpyxl
